"""empty message

Revision ID: 788784ac36d7
Revises: 
Create Date: 2026-05-19 22:44:16.402080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788784ac36d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tvoc', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pm1', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_column('pm1')
        batch_op.drop_column('tvoc')

    # ### end Alembic commands ###
